

# Twitter application authentication
def APP_KEY(): 
	APP_KEY = 'YOUR_APP_KEY'
	return APP_KEY

def APP_SECRET(): 
	APP_SECRET = 'YOUR_APP_SECRET'
	return APP_SECRET

def OAUTH_TOKEN(): 
	OAUTH_TOKEN = 'YOUR_OAUTH_TOKEN'
	return OAUTH_TOKEN

def OAUTH_TOKEN_SECRET(): 
	OAUTH_TOKEN_SECRET = 'YOUR_OAUTH_TOKEN_SECRET'
	return OAUTH_TOKEN_SECRET